spring:
  application:
    name: score-system

  datasource:
    # 数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://47.122.78.242:3306/student_score_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456

  servlet:
    multipart:
      # 文件上传配置
      max-file-size: 10MB
      max-request-size: 20MB
    
    # Session配置
    session:
      cookie:
        # SameSite属性设置为None以支持跨域请求携带Cookie
        same-site: none
        # 启用安全标志，当使用HTTPS时必须设置
        secure: false
        # Cookie路径
        path: /
        # Cookie有效期（30分钟）
        max-age: 1800

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 自动驼峰命名转换
  mapper-locations: classpath*:/mapper/**/*.xml  # XML 映射文件路径
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.wtu.entity

springdoc:
  api-docs:
    # OpenAPI 文档路径
    path: /v3/api-docs
  swagger-ui:
    # Swagger UI 页面路径
    path: /swagger-ui.html
knife4j:
  # 启用 Knife4j
  enable: true
  # 开发环境下设置为 false
  production: false

logging:
  level:
    com:
      wtu:
        # 日志级别
        mapper: debug
        service: info
        controller: info

server:
  port: 8080
  servlet:
    context-path: /
    # 添加Session配置
    session:
      cookie:
        name: JSESSIONID
        http-only: true